spring:
  application:
    name: federation-api

  datasource:
    url: jdbc:postgresql://localhost:5432/springboot
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  flyway:
    enabled: false

server:
  port: 8080